services:
    PhPhD\ExceptionToolkit\Unwrapper\ExceptionUnwrapper:
        public: true
        class: PhPhD\ExceptionToolkit\Unwrapper\ExceptionUnwrapper
        factory:
            - !service_locator
                stack: '@phd_exception_toolkit.exception_unwrapper.stack'
            - get
        arguments: [ stack ]
        lazy: true
